### ISSUE TITLE
Enable sponsorship

### ISSUE THREAD

**Issue by XVilka** [chvp/NanoLedger#128]
Looks like it's the only active mobile app for hledger. I am sure many hledger users, including myself, would be happy to chip in.

**Comment by chvp** [comment]
While I appreciate the sentiment, I honestly don't feel the need to be rewarded for the work I did on this app. I created it for myself and made it open-source so others could benefit. If anyone really feels like giving money away, please give money to your local Red Cross instance. Or donate to the one I volunteer at, if you really want to: https://www.rodekruis.be/afdeling/gent/wat-kan-jij-doen/steun-financieel/ (only available in Dutch, sadly).
