### ISSUE TITLE
Amount parsing crashes when the amount contains only an assertion

### ISSUE THREAD

**Issue by andreasrohnerdotnet** [chvp/NanoLedger#187]
##### Reproduction steps

  1. Update NanoLedger from v0.4.6 to v0.6.0 via Obtainium (i.e. from GitHub)
  2. Start NanoLedger
  3. NanoLedger opens briefly without loading the ledger and and closes almost immediately
  4. Get Android error message "NanoLedger keeps stopping" (cf. screenshot)
![Screenshot_20241006-071155_Trebuchet](https://github.com/user-attachments/assets/cf563cf6-3a85-4175-a88e-4431c5e1421c)

##### Expected behaviour

Keep working as reliably as the previous versions.

##### System information

- **Device:** Xiaomi Poco X3 Pro
- **OS Version:** LineageOS 20 (Android 13)
- **App Version:** NanoLedger v0.6.0

##### Additional Context

My ledger is synced via Nextcloud.

Last, but not least, I want to take a moment to express my gratitude for your hard work and dedication to this amazing app. NanoLedger helps make plain text accounting a breeze.

**Comment by andreasrohnerdotnet** [comment]
After clearing the NanoLedger's storage and cache NanoLedger v0.6.0 opens without issue.

However, the app crashes immediately after configuring the file in Settings » File by setting it to my ledger file (.txt) on my Nextcloud instance (content://org.nextcloud.documents/document/[string of numbers, letters and special charactes, e.g. % ]

**Comment by chvp** [comment]
Hmm, that's not great. Since I had to parse the amounts for the edit functionality, I probably didn't cover an edge case there. 

How familiar are you with android development? Any chance you could use `adb logcat` to get the logs for this crash?

And I know this is a lot to ask, but any chance you could share your journal file? If you don't want to share the whole file, you could try to minimise a reproduction sample by throwing away half of the transactions and seeing if the bug still occurs. If it does, keep going, if it doesn't, take the other half and keep going with those transactions.

**Comment by andreasrohnerdotnet** [comment]
I am not familiar with Android development, unfortunately. However, I tried my best with `adb logcat | grep be.chvp.nanoledger > ~/Downloads/crash_logs_nanoledger060.txt` and my original hledger-file, a .txt-file with 731 transactions and a size of 153kB (cf. log-file attached 
[crash_logs_nanoledger060.txt](https://github.com/user-attachments/files/17268994/crash_logs_nanoledger060.txt).) Before running `adb logcat` I made sure that the my inputs are valid by running hledger in strict mode (i.e. `hledger --strict`).

As you suggested, I tried to reproduce the crashes with a reduced ledger file. Iterating over my hledger-file, it turned out that my opening balance statement was the culprit.

Setting opening balances according to https://hledger.org/1.40/hledger.html#setting-opening-balances **does work in NanoLedger v0.6.0**:

```txt
include ./accounts.txt
include ./commodities.txt
include ./prices.txt
include ./budget.txt

; Setting opening balances according to https://hledger.org/1.40/hledger.html#setting-opening-balances does work in NanoLedger v0.6.0
2016/1/1 opening balances
  assets:checking           $409.32 = $409.32
  assets:savings            $735.24 = $735.24
  assets:cash               $42  = $42
  equity:opening balances
```

Setting opening balances according to https://hledger.org/1.40/hledger.html#balance-assignments **does not work in NanoLedger v0.6.0**:

```txt
include ./accounts.txt
include ./commodities.txt
include ./prices.txt
include ./budget.txt
  
  ; Setting opening balances according to https://hledger.org/1.40/hledger.html#balance-assignments does not work in NanoLedger v0.6.0
2016/1/1 opening balances
  assets:checking            = $409.32
  assets:savings             = $735.24
  assets:cash                 = $42
  equity:opening balances
```

So the problem seems to be the parsing of Ledger-style balance assignments.

**Comment by chvp** [comment]
Ah right, that's a thing as well. I'll try to work on a fix ASAP.

**Comment by chvp** [comment]
Thanks for the help in diagnosing this issue! I worked on a fix in #188. Could you give the following APK a try? https://github.com/chvp/NanoLedger/actions/runs/11201905084/artifacts/2020684183

**Comment by andreasrohnerdotnet** [comment]
I'm happy to report that your solution resolved this issue.

Thank you so much for your quick response and fix!

**Comment by chvp** [comment]
Great! I pushed the tag for a new release, it should be created automatically in a few minutes.
