### ISSUE TITLE
Cursor in pre-filled negative amount field is confusing

### ISSUE THREAD

**Issue by alerque** [chvp/NanoLedger#73]
Having the remaining amount needed to balance a transaction show up is a nice touch, but it's actually kind of confusing to us. The "grey" is so subtly different from the actual value color it isn't always apparent unless I squint what element is a preview value and what is actually filled in.

This makes it super confusing what is happening when you add a second transaction with a blank amount. Now it isn't really obvious that both are blank.

Also when taping into the field, the cursor is displayed in the center of the input which is in the center of the preview amount. That's really confusing, and I kept trying to move the cursor or select the text that was there.

1. The preview amount needs more visual distinction, maybe more color contrast or maybe some other treatment (e.g. not drawing the input field box?).
1. Focusing on the input field should completely remove the preview amount from the background. Since a new input line gets added anyway, the unbalanced/preview amount should probably move to the *empty* transaction not the one being currently edited. Then if the amount box isn't focused it can be moved to where the implied amount it would actually be applied.

**Comment by chvp** [comment]
Yeah, I've noticed that as well, especially in dark mode. I use the default Material You colors, but I guess they weren't necessarily meant for text. Moving the preview amount when the box is focused is a good idea.
