### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by opk12** [chvp/NanoLedger#95]
I would like to repurpose two old Samsung phones with Android 5 and Android 7.1. Would you consider lowering the minimum Android version? I'm not an Android dev and don't know if it's feasible though. Thank you.

**Comment by chvp** [comment]
I made a PR to do this here: https://github.com/chvp/NanoLedger/pull/96/. The oldest version I was able to test with was Android 7.0 (there are no x86 emulator images below that version). But there shouldn't be any reason the app would work on 7.0 and not on 5.
